# team01-be values
template:
  nameOverride: "team01-be"
  fullnameOverride: "team01-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team01-be-development-repo
    pullPolicy: Always
    tag: "sha-382a7e2"

  vault:
    enabled: true
    environment: "dev"

  serviceAccountName: "team01-be"

  env: {}
