# team02-be values
template:
  nameOverride: "team02-be"
  fullnameOverride: "team02-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team02-be-development-repo
    pullPolicy: Always
    tag: "sha-769ed48"

  vault:
    enabled: true
    environment: "dev"

  prometheus:
    enabled: true
    scrape: "true"
    path: "/actuator/prometheus"
    port: "8080"

  serviceAccountName: "team02-be"

  env: {}
