apiVersion: v2
name: msa-test1
description: A Helm chart for MSA Test1 Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: template
    version: "*"
    repository: "file://../../common/template"
