apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-test2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <https://github.com/TP1-OuterMSA/msa-infra.git\>
    targetRevision: HEAD
    path: charts/services/msa-test2
  destination:
    server: <https://kubernetes.default.svc\>
    namespace: msa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
