# team03-be values
template:
  nameOverride: "team03-be"
  fullnameOverride: "team03-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team03-be-development-repo
    pullPolicy: Always
    tag: "sha-6136e5b"

  vault:
    enabled: true
    environment: "dev"

  env: {}
