# team04-be values
template:
  nameOverride: "team04-be"
  fullnameOverride: "team04-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team04-be-development-repo
    pullPolicy: Always
    tag: "sha-7fb2a57"

  vault:
    enabled: true
    environment: "dev"

  serviceAccountName: "team04-be"

  env: {}
