# team05-be values
template:
  nameOverride: "team05-be"
  fullnameOverride: "team05-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team05-be-development-repo
    pullPolicy: Always
    tag: "sha-e97ee32"

  vault:
    enabled: true
    environment: "dev"

  serviceAccountName: "team05-be"

  env: {}
