apiVersion: v1
kind: Secret
metadata:
  name: team03-ai-agent-secrets
  namespace: msa
type: Opaque
data:
  django-secret: ZGphbmdvLWluc2VjdXJlLSEodDZwMmFudmx0OWFyNzg9cSZudmZsYz11K2RvNSg1eG43NTJzOWwmJis=
  openai-api-key: c2stcHJvai1nTnQyd2lKaEk1T0ZTSmx0STF1MGpLbUhrVkpLdk45QUptbFRGRWYzWEgtYzZuUW9NU0VsZVZES1FNeFhwTFFzQjF0U2g1NDlPV1QzQmxia0ZKMnFrWFBXZWplNzBQdV9VV1VaY3ZqcmpKTGRZN0VOM0xUa3Y3cGtjOE5DMFdMekp6MmQ5THdNN1ZlSjZETDIwMWtpdUVWVnhMa0E=
