# team06-be values
template:
  nameOverride: "team06-be"
  fullnameOverride: "team06-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team06-be-development-repo
    pullPolicy: Always
    tag: "sha-2ac205d"

  vault:
    enabled: true
    environment: "dev"

  serviceAccountName: "team06-be"

  env: {}
