# team06-be values
template:
  nameOverride: "team06-be"
  fullnameOverride: "team06-be"

  strategy:
    type: Recreate

  image:
    repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team06-be-development-repo
    pullPolicy: Always
    tag: "sha-c6c0503"

  vault:
    enabled: true
    environment: "dev"

  prometheus:
    enabled: true
    scrape: "true"
    path: "/actuator/prometheus"
    port: "8080"

  serviceAccountName: "team06-be"

  env: {}
